// Barrel for the API module: later epics import the client and its shared types
// from `../api` rather than reaching into individual files.

export { ApiError } from "./client";
export {
  assumePersona,
  claimLead,
  convertLead,
  createLead,
  getConversion,
  getCurrentIdentity,
  getDemoSession,
  getHouseholds,
  getLead,
  getLeadTimeline,
  listLeads,
  listTenants,
  qualifyLead,
  rejectLead,
  resetDemoSession,
  resolveDuplicate,
  revealLeadField,
  signOut,
  submitPublicIntake,
} from "./client";
export type {
  Capability,
  ConversionSummary,
  ConvertLeadRequest,
  CreateLeadRequest,
  HouseholdChoice,
  HouseholdSearchResult,
  DemoSessionResetResult,
  DemoSessionState,
  DemoSessionStatus,
  DuplicateResolution,
  Identity,
  IdentityUser,
  LeadSource,
  LeadStatus,
  MaskedLead,
  ProductLine,
  PublicIntakeRequest,
  PublicIntakeResult,
  RejectLeadRequest,
  ResolveDuplicateAction,
  ResolveDuplicateRequest,
  RevealableField,
  RevealLeadRequest,
  RevealLeadResponse,
  Role,
  ReactionStatus,
  Tenant,
  TimelineEventRow,
  TimelineReactionRow,
  TimelineRow,
} from "./types";
