// Barrel for the API module: later epics import the client and its shared types
// from `../api` rather than reaching into individual files.

export { ApiError } from "./client";
export {
  assumePersona,
  claimLead,
  convertLead,
  createLead,
  getConversion,
  getConversionPrefill,
  getCurrentIdentity,
  getDemoSession,
  getHouseholds,
  changeOpportunityStage,
  getLead,
  getLeadTimeline,
  getOpportunityBoard,
  getOpportunityPolicy,
  listLeads,
  listTasks,
  completeTask,
  listTenants,
  qualifyLead,
  rejectLead,
  requestQuotes,
  getQuoteRequest,
  selectQuote,
  patchApplication,
  submitApplication,
  revealMedicareId,
  resetDemoSession,
  runAepSweep,
  runAnniversarySweep,
  resolveDuplicate,
  revealLeadField,
  signOut,
  submitPublicIntake,
} from "./client";
export type {
  RenewalSweepResult,
  Application,
  Capability,
  ConversionPrefill,
  ConversionSummary,
  ConvertLeadRequest,
  CreateLeadRequest,
  HouseholdChoice,
  HouseholdSearchResult,
  DemoSessionResetResult,
  DemoSessionState,
  DemoSessionStatus,
  DuplicateResolution,
  Identity,
  IdentityUser,
  LeadSource,
  LeadStatus,
  MaskedLead,
  OpportunityBoard,
  OpportunityEligibility,
  OpportunityRow,
  PipelineStage,
  Policy,
  ProductLine,
  PublicIntakeRequest,
  PublicIntakeResult,
  QuoteOption,
  QuoteRequestPoll,
  QuoteRequestSummary,
  RejectLeadRequest,
  ResolveDuplicateAction,
  ResolveDuplicateRequest,
  RevealableField,
  RevealLeadRequest,
  RevealLeadResponse,
  Role,
  ReactionStatus,
  Task,
  Tenant,
  TimelineEventRow,
  TimelineReactionRow,
  TimelineRow,
} from "./types";
