"""Migration-health proofs for the Alembic gate (Epic 9).

Two guarantees, both run against the same Dockerised Postgres substrate as
`test_tenant_schemas.py` (the session-scoped `database_engine` fixture leaves the
container migrated to head), and both drive Alembic through the same
`alembic.command` + `Config` idiom `conftest.py` uses:

- **No drift:** with the schema filter from `alembic/env.py` in place,
  `alembic check` reports zero new upgrade operations — the migration-owned
  tenant schemas (`sunshine` / `florida`), Postgres's built-in schemas, and the
  schema-less demonstrator tables (`tenant_settings`, `pii_demo`) no longer
  surface as phantom drift.
- **Round-trip:** `alembic downgrade base` then `alembic upgrade head` both
  succeed and the database ends back at head, proving the migrations reverse and
  replay cleanly. Head is restored before returning so the shared container is
  left exactly as other tests expect (pytest runs serially, so the transient
  downgrade is never observed by another test).

Each test points `DATABASE_URL` at the container while it drives Alembic and
resets it in a `finally`, the same pattern `conftest.py` uses, so the env var
never leaks between tests. The tests also depend on the `database_engine` fixture
so the container is migrated to head before they run, and so the env.py filter
under test is the one exercised by the substrate the rest of the suite uses.
"""

import os
from contextlib import contextmanager

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine

from tests.conftest import (
    ALEMBIC_CONFIG_PATH,
    CORE_ROOT,
    build_postgresql_url,
)


def build_alembic_config() -> Config:
    """Build an Alembic `Config` pointed at the core package's migration scripts.

    Mirrors the `database_engine` fixture in `conftest.py`: the same `alembic.ini`
    and `alembic/` script location, so the commands run exactly as production does.
    """
    alembic_config = Config(str(ALEMBIC_CONFIG_PATH))
    alembic_config.set_main_option("script_location", str(CORE_ROOT / "alembic"))
    return alembic_config


@contextmanager
def database_url_pointed_at(container):
    """Set `DATABASE_URL` to the container while Alembic runs, then restore it.

    `alembic/env.py` reads `DATABASE_URL`, so each command needs it pointed at the
    test container. The previous value is restored in a `finally` — the same
    no-leak pattern the `database_engine` fixture in `conftest.py` uses.
    """
    database_url = build_postgresql_url(container)
    previous_database_url = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = database_url
    try:
        yield database_url
    finally:
        if previous_database_url is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous_database_url


def to_synchronous_url(database_url: str) -> str:
    """Rewrite a driverless `postgresql://` URL to the sync psycopg driver.

    The same scheme `alembic/env.py` rewrites to internally; used here only to
    read `alembic_version` directly for the round-trip head assertion.
    """
    return "postgresql+psycopg://" + database_url[len("postgresql://"):]


def get_current_database_revision(synchronous_database_url: str) -> str | None:
    """Return the revision the database is currently stamped at, or `None`.

    Reads `alembic_version` through a short-lived synchronous engine (the psycopg
    driver Alembic itself uses), so the check observes exactly what migrations see.
    """
    engine = create_engine(synchronous_database_url)
    try:
        with engine.connect() as connection:
            migration_context = MigrationContext.configure(connection)
            return migration_context.get_current_revision()
    finally:
        engine.dispose()


def test_alembic_check_reports_no_drift(database_engine, postgres_container):
    """`alembic check` finds zero drift once the env.py schema filter is applied.

    The `database_engine` fixture has already migrated the container to head.
    `command.check` raises `AutogenerateDiffsDetected` if the models and the live
    database disagree, so completing without raising is the assertion: the
    Phase-1 filter leaves no phantom drift from the tenant schemas or the
    schema-less demonstrator tables (`tenant_settings`, `pii_demo`).
    """
    with database_url_pointed_at(postgres_container):
        # Raises AutogenerateDiffsDetected on drift; no raise means no drift.
        command.check(build_alembic_config())


def test_migrations_round_trip_down_to_base_and_back_to_head(
    database_engine, postgres_container
):
    """`downgrade base` then `upgrade head` both succeed and end back at head.

    Proves the migrations reverse cleanly and replay idempotently (re-running
    `0003`–`0006` recreates the tenant schemas, roles, the per-tenant
    `tenant_settings` / `pii_demo` tables, their indexes, and grants). Head is
    restored before returning so the shared session-scoped container is left
    exactly as the rest of the suite expects.
    """
    alembic_config = build_alembic_config()

    with database_url_pointed_at(postgres_container) as database_url:
        synchronous_database_url = to_synchronous_url(database_url)
        head_revision = get_current_database_revision(synchronous_database_url)

        try:
            command.downgrade(alembic_config, "base")
            assert get_current_database_revision(synchronous_database_url) is None

            command.upgrade(alembic_config, "head")
            assert (
                get_current_database_revision(synchronous_database_url)
                == head_revision
            )
        finally:
            # Restore head no matter what so other tests see a migrated container.
            command.upgrade(alembic_config, "head")
